#!/bin/bash

if [[ -z "$SLACK_WEBHOOK" ]] 
then
    echo "Env variable SLACK_WEBHOOK is not set"
    exit 1
fi

curl -X POST -H "Content-Type: application/json" --data '{"text": "'"$1"'"}' $SLACK_WEBHOOK
